---
output:
  html_document:
    self-contained: true
    number_sections: false
    toc: true
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  comment = "",
  warning = FALSE,
  message = FALSE
  # echo = FALSE
)
```

# Introdução

Este relatório se dedica a analisar os registros de apreensões de psicoativos no Espírito Santo, realizados por órgãos importantes da segurança pública, sendo eles: Polícia Federal, Polícia Rodoviária Federal e Polícia Estadual. Além disso, busca avaliar o impacto do programa Estado Presente, implementado pelo governo do estado em 28/12/2017.  

Segundo a Secretaria de Estado de Direitos Humanos, o projeto visa à redução dos índices de criminalidade, principalmente homicídios e roubos, em regiões de maior vulnerabilidade social. As cidades de Aracruz, Guarapari, Cariacica, Colatina, Linhares, São Mateus, Serra, Vila Velha e Vitória fazem parte do Estado Presente, que é aplicado em bairros específicos desses municípios.  

É importante ressaltar que o Projeto Estado Presente é implementado em bairros específicos dentro dos municípios, e não no município como um todo. Portanto, as análises apresentadas podem estar mascaradas, uma vez que agregam dados de áreas não contempladas pelo programa. Por exemplo, considerar todo o município de Vitória na análise pode diluir os efeitos observados nos bairros-alvo, como Nova Palestina.

Abaixo, apresentamos a lista dos bairros atendidos pelo programa:


-   Nova Palestina, Bairro da Penha e Piedade (Vitória);
-   Barramares, Ulisses Guimarães, Boa Vista (I e II), São Torquato e Santa Rita (Vila Velha);
-   Feu Rosa, Vila Nova de Colares, Jardim Carapina, Novo Horizonte, Planalto Serrano, Central - Carapina e Bairro das Laranjeiras (Serra);
-   Castelo Branco, Nova Rosa da Penha, Flexal II e Nova Esperança (Cariacica);
-   Adalberto S. Nader e Kubitschek (Guarapari);
-   Zumbi e Village da Luz (Cachoeiro de Itapemirim);
-   Jacupemba (Aracruz);
-   Ayrton Senna e Bela Vista (Colatina);
-   Interlagos e Aviso (Linhares);
-   Vila Nova e Bom Sucesso (São Mateus).

Para uma análise com rigor estatístico, foram implementados diversos métodos de visualização para dados temporalmente associados, assim como foram realizados testes estatísticos para avaliar se houve mudanças relevantes após a implementação do programa.  
Paralelamente, devido à falta de discriminação em nível de município nos registros do banco de dados disponibilizados pela Polícia Federal e pela Polícia Estadual, não foi possível avaliar o desempenho do projeto com esses dados, sendo realizada apenas uma análise geral do desempenho do Espírito Santo. Os dados disponibilizados pela Polícia Rodoviária Federal são discriminados em nível municipal, entretanto, não são discriminados em nível de bairro/distrito. Devido a esse fato, adotou-se uma abordagem generalista para representar o impacto do projeto, utilizando dados municipais.  
