---
output:
  html_document:
    self-contained: true
    number_sections: false
    toc: true
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  comment = "",
  warning = FALSE,
  message = FALSE
  # echo = FALSE
)
```

# Conclusão

Este relatório analisou os registros de apreensões de substâncias psicoativas no Espírito Santo realizados pela Polícia Federal, Polícia Rodoviária Federal e Polícia Estadual, com o objetivo de avaliar o impacto do programa Estado Presente implementado em 28/12/2017. Observou-se que a Polícia Federal concentrou suas maiores apreensões de cocaína em portos e aeroportos, enquanto a Polícia Federal e Estadual tiveram maior volume de apreensões de maconha em operações terrestres. Visualmente, os dados sugerem um aumento nas apreensões tanto pela Polícia Federal quanto pela Polícia Estadual.

As limitações nos dados disponíveis dificultaram uma análise mais aprofundada e conclusiva sobre a eficácia do programa. A ausência de discriminação a nível municipal nos registros da Polícia Federal e da Polícia Estadual impediu uma avaliação localizada do projeto, restringindo a análise a uma perspectiva estadual geral. Além disso, a falta de informações detalhadas antes da implementação do programa em 2017 comprometeu a comparação temporal necessária para uma conclusão robusta.

Apesar dessas limitações, os dados revelaram uma tendência de aumento nas apreensões de cocaína pela Polícia Estadual em nível estadual. Geograficamente, a maioria das apreensões concentraram-se na região Central e Litoral. Embora esses indícios sugiram uma maior efetividade na atuação policial após a implantação do Estado Presente, essa hipótese não pode ser confirmada estatisticamente devido à escassez de dados prévios e à ausência de informações mais granularizadas que permitissem isolar o efeito do programa de outras variáveis.
